// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIa_LCNkt-yD_GrHAkOxxqSdVbPXo_80g',
    appId: '1:807783646927:web:bae8ed7dec31580b77d9ba',
    messagingSenderId: '807783646927',
    projectId: 'mynotes-app-patchstudio',
    authDomain: 'mynotes-app-patchstudio.firebaseapp.com',
    storageBucket: 'mynotes-app-patchstudio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGUSi7wb057rJ1rd69Y3OMrCibS93veDI',
    appId: '1:1049228270283:android:e5ea237f8e1722e888d94e',
    messagingSenderId: '1049228270283',
    projectId: 'mynotes-patchstudio-project',
    storageBucket: 'mynotes-patchstudio-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPnhSLWyy5BGXSUDEypbTYdGjyYyC6Nok',
    appId: '1:1049228270283:ios:b5662094c4ab24c788d94e',
    messagingSenderId: '1049228270283',
    projectId: 'mynotes-patchstudio-project',
    storageBucket: 'mynotes-patchstudio-project.firebasestorage.app',
    iosBundleId: 'com.patchstudio.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaY5teTj_r65_CYBqe0hX9lzKMJbT6DBY',
    appId: '1:807783646927:ios:a9ffe3f0399c212977d9ba',
    messagingSenderId: '807783646927',
    projectId: 'mynotes-app-patchstudio',
    storageBucket: 'mynotes-app-patchstudio.firebasestorage.app',
    iosBundleId: 'com.patchstudio.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBlO8iNXusy0T1QEvoXssng9ZoWE0TdqM',
    appId: '1:1049228270283:web:7a4678fed157321d88d94e',
    messagingSenderId: '1049228270283',
    projectId: 'mynotes-patchstudio-project',
    authDomain: 'mynotes-patchstudio-project.firebaseapp.com',
    storageBucket: 'mynotes-patchstudio-project.firebasestorage.app',
  );

}